### PR TITLE
[ZEPPELIN-5141]. Solve the incompatibility issue of hive below 2.3

### PR DESCRIPTION
**Pull request by zhengslei**
### What is this PR for?
The current hive interpreter (jdbc) cannot work with hive below 2.3.  The code "hiveStmt.setInPlaceUpdateStream(InPlaceUpdateStream stream)" in HiveUtils uses InPlaceUpdateStream class which is only available in version 2.3 or above, which leads to runtime NoClassDefFoundError.  Move the code into ProgressBar to delay NoClassDefFoundError of InPlaceUpdateStream until ProgressBar instanced. When hive < 2.3, ProgressBar will not be instanced, so it works well.

### What type of PR is it?
[Bug Fix | Improvement ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5141

### How should this be tested?
* Test the hive interpreter(jdbc) with version both above 2.3 and below 2.3 to check whether it can work well.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @zhengslei LGTM
