### PR TITLE
[ZEPPELIN-605] Add support for Scala 2.11

### PR DESCRIPTION
**Pull request by lresende**
Enable Zeppelin to be built with both Scala 2.10
and Scala 2.11, mostly to start supporting interpreters
that are moving to Scala 2.11 only such as Spark.

Before testing this PR, one would need to [build Spark 1.6.1 for example with Scala 2.11](http://spark.apache.org/docs/latest/building-spark.html#building-for-scala-211) and [build Flink 1.0 with Scala 2.11](https://ci.apache.org/projects/flink/flink-docs-master/setup/building.html#scala-versions)

### CODE REVIEW

File: flink/pom.xml [hunk 1]
```diff
@@ -97,44 +95,44 @@
 
     <dependency>
       <groupId>com.typesafe.akka</groupId>
-      <artifactId>akka-actor_${flink.scala.binary.version}</artifactId>
+      <artifactId>akka-actor_${scala.binary.version}</artifactId>
```
Comment (felixcheung) [inline flink/pom.xml]: there might still be a need for interpreter individually requiring different version of Scala? I think for now it might make sense to have separate `flink.scala`, `ignite.scala` and so on

File: spark/pom.xml [hunk 2]
```diff
@@ -36,10 +36,17 @@
...
     <spark.version>1.4.1</spark.version>
-    <scala.version>2.10.4</scala.version>
-    <scala.binary.version>2.10</scala.binary.version>
   </properties>
 
+  <profiles>  
+    <profile>
+      <id>scala-2.11</id>    
+      <properties>
+        <spark.version>2.0.0-SNAPSHOT</spark.version>
```
Comment (felixcheung) [inline spark/pom.xml]: not sure that would work - we could need the artifact in maven central repo or similar to build, and snapshot builds are not published..

Comment (lresende) [inline spark/pom.xml]: Agree, i was just trying to use a spark compiled with scala 2.11 and what i had locally was trunk. This is still work in progress.

File: flink/pom.xml (hunk 1 above)
Comment (lresende) [inline flink/pom.xml]: What would be the case for having interpreter specific scala versions ? Now it seems that everything work with latest scala 2.10. I am more towards simplifying the build now, and making it more complex when actually needed.  Do we have a concrete case where this is needed now ?

 If we are talking here about actually scala 2.10 versus 2.11, I plan to handle that by profiles/modules.

Comment (felixcheung) [inline flink/pom.xml]: Yes, I was referring to `flink.scala.binary.version`, `ignite.scala.binary.version`.
Maybe Ignite doesn't support Scala 2.11? https://github.com/apache/ignite/blob/master/pom.xml#L453

**Comment by lresende** [comment]
The current status of this PR is that it's working ok with Scala 2.10 and Scala 2.11, I need to try to have one source for both versions of scala, and also rebase to pickup the most recent projects added to trunk

**Comment by adeandrade** [comment]
Hi @lresende, I rebased the PR and created a package with:

`mvn clean package -Pbuild-distr -Pscala-2.11 -Pspark-1.6 -Phadoop-2.6 -Pyarn -Ppyspark -Dscala-2.11 -DskipTests -Dcheckstyle.skip=true clean install`

But I still don't have access to a SparkContext instance:

> java.lang.NoSuchMethodException: scala.tools.nsc.interpreter.ILoop$ILoopInterpreter.classServerUri()
	at java.lang.Class.getMethod(Class.java:1786)
	at org.apache.zeppelin.spark.SparkInterpreter.createSparkContext(SparkInterpreter.java:276)
	at org.apache.zeppelin.spark.SparkInterpreter.getSparkContext(SparkInterpreter.java:150)
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:518)
	at org.apache.zeppelin.interpreter.ClassloaderInterpreter.open(ClassloaderInterpreter.java:74)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:68)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:92)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:345)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:176)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

Any ideas?

Thanks.

**Comment by felixcheung** [comment]
@adeandrade this seems to be a breaking change in Spark 2.0, also being fixed in #868

**Comment by karup1990** [comment]
@adeandrade is ur spark binary compiled with scala-2.11, else it will continue to use the repl classes from scala-2.10(https://issues.apache.org/jira/browse/SPARK-1812 ) and you would hit the exception.
I was able to consume this PR and use Zeppelin with spark 1.5 compiled with scala-2.11.

**Comment by adeandrade** [comment]
@karup1990 Yes, it is. Did you rebase with master? I think it works if you don't. @felixcheung suggests the problem is being fixed in #868. I'm waiting for that PR to be merged to try again. If it doesn't work then I'll fall back to your suggestion. Thanks.

**Comment by lresende** [comment]
Sorry to not be so responsive here, I was busy with conferences, etc... but should be able to devote some time to this again. 

This should work if you don't rebase, otherwise we need to update the new modules such as R extensions to properly work on Scala 2.11. Note that one way or another, you probably need to build Spark and Flink with Scala 2.11 and make sure you use maven "install" and not only "package".
If folks are eager to try it, i can try to rebase, while I work on the final version of this PR, which will try to merge the two scala 2.10 and 2.11 into one code, using some reflection magic.

**Comment by lresende** [comment]
@Leemoonsoo @felixcheung Any ideas what might be causing these build issues in [TravisCI](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133750597/log.txt) ?

 
[INFO] Running 'npm install --color=false' in /home/travis/build/apache/incubator-zeppelin/zeppelin-web
[ERROR] npm WARN package.json zeppelin-web@0.0.0 No license field.
[ERROR] npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[ERROR] npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
[ERROR] npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[ERROR] npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[ERROR] npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
[ERROR] npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
[ERROR] npm WARN optional dep failed, continuing fsevents@1.0.12
[INFO] 
[INFO] > phantomjs@1.9.20 install /home/travis/build/apache/incubator-zeppelin/zeppelin-web/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
[INFO] > node install.js

**Comment by felixcheung** [comment]
it looks like error with NPM?

```
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] 
[ERROR] npm ERR! shasum check failed for /tmp/npm-10098-08b17b7f/registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
[ERROR] npm ERR! Expected: a567c2af000ad22dc8f2a653d91978ae1f5316f4
[ERROR] npm ERR! Actual:   2f4894420f76a8277eeaf59a8c94ca43623484bd
[ERROR] npm ERR! From:     https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ECONNRESET
[ERROR] npm ERR! errno ECONNRESET
[ERROR] npm ERR! syscall read
[ERROR] 
[ERROR] npm ERR! network read ECONNRESET
[ERROR] npm ERR! network This is most likely not a problem with npm itself
[ERROR] npm ERR! network and is related to network connectivity.
[ERROR] npm ERR! network In most cases you are behind a proxy or have bad network settings.
[ERROR] npm ERR! network 
[ERROR] npm ERR! network If you are behind a proxy, please make sure that the
[ERROR] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ECONNRESET
[ERROR] npm ERR! errno ECONNRESET
[ERROR] npm ERR! syscall read
[ERROR] 
[ERROR] npm ERR! network read ECONNRESET
[ERROR] npm ERR! network This is most likely not a problem with npm itself
[ERROR] npm ERR! network and is related to network connectivity.
[ERROR] npm ERR! network In most cases you are behind a proxy or have bad network settings.
[ERROR] npm ERR! network 
[ERROR] npm ERR! network If you are behind a proxy, please make sure that the
[ERROR] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ECONNRESET
[ERROR] npm ERR! errno ECONNRESET
[ERROR] npm ERR! syscall read
[ERROR] 
[ERROR] npm ERR! network read ECONNRESET
[ERROR] npm ERR! network This is most likely not a problem with npm itself
[ERROR] npm ERR! network and is related to network connectivity.
[ERROR] npm ERR! network In most cases you are behind a proxy or have bad network settings.
[ERROR] npm ERR! network 
[ERROR] npm ERR! network If you are behind a proxy, please make sure that the
[ERROR] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ECONNRESET
[ERROR] npm ERR! errno ECONNRESET
[ERROR] npm ERR! syscall read
[ERROR] 
[ERROR] npm ERR! network read ECONNRESET
[ERROR] npm ERR! network This is most likely not a problem with npm itself
[ERROR] npm ERR! network and is related to network connectivity.
[ERROR] npm ERR! network In most cases you are behind a proxy or have bad network settings.
[ERROR] npm ERR! network 
[ERROR] npm ERR! network If you are behind a proxy, please make sure that the
[ERROR] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ECONNRESET
[ERROR] npm ERR! errno ECONNRESET
[ERROR] npm ERR! syscall read
[ERROR] 
[ERROR] npm ERR! network read ECONNRESET
[ERROR] npm ERR! network This is most likely not a problem with npm itself
[ERROR] npm ERR! network and is related to network connectivity.
[ERROR] npm ERR! network In most cases you are behind a proxy or have bad network settings.
[ERROR] npm ERR! network 
[ERROR] npm ERR! network If you are behind a proxy, please make sure that the
[ERROR] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/travis/build/apache/incubator-zeppelin/zeppelin-web/npm-debug.log
[INFO]                                                        
```

**Comment by Leemoonsoo** [comment]
I think it's temporary failing. npm ERR will disappear when trigger CI again

**Comment by pabloa** [comment]
Hello @lresende,

I tried your pull request and I am getting some NPE. Notebooks are not stored either. I tried the branch scala-210-211-NEW and I am getting compilation errors.

Do you have some estimated time about getting a testable version of Zeppelin under 2.11? I will be happy to test it and report feedback.

**Comment by Leemoonsoo** [comment]
Still working in progress, created a pullrequest to this branch, https://github.com/lresende/incubator-zeppelin/pull/1 which is trying to merge 2.10 and 2.11 code using reflection

**Comment by chbrown** [comment]
I just tried out the `scala-210-211-rebased-moon` branch from `lresende/incubator-zeppelin.git` and it seems to be working, using Spark 1.6.1 built from source for Scala 2.11.8, but I ran into several web interface issues:
* the interpreter settings page won't let me commit changes (console error: "scripts.js:1 Uncaught TypeError: Cannot read property 'propertyKey' of undefined"), so I had to set the `master` value directly in `conf/interpreter.json`
* notebooks are not persisted, and the notebook import feature doesn't work (no discernible error message)

Are these known issues, given that `scala-210-211-rebased-moon` isn't too far off master, or are they something that would be useful to look into fixing?

**Comment by Leemoonsoo** [comment]
@chbrown Thanks for testing and sharing problem. Let me see how interpreter setting page and notebook persistent problem can be fixed in this branch.

**Comment by Leemoonsoo** [comment]
@lresende I have merged both scala 2.11 and 2.10 on lresende#1. Could you take a look and merge if you think it is good?  CI is keep failing on download spark packages.

After merge lresende#1, it's good idea to merge master to fix problem reported @chbrown and CI failure. If CI continues to fail after merge master, i can take a look.

**Comment by lresende** [comment]
Thank you @Leemoonsoo, let me look at this tonight/tomorrow morning. And provide any findings on the reported issues.

**Comment by lresende** [comment]
@Leemoonsoo this is now merged and rebased, will still do some test and investigate the issues reported. Others are welcome to help testing as well.

**Comment by prasadwagle** [comment]
@lresende I am getting a compiler error "package MutableSettings does not exist". This is the same error in the travis ci build. Here are the build commands I used.
```
tw-172-25-130-145 incubator-zeppelin-prasadwagle (master) $ git fetch upstream pull/747/head:scala211_2
tw-172-25-130-145 incubator-zeppelin-prasadwagle (master) $ git checkout scala211_2

tw-172-25-130-145 incubator-zeppelin-prasadwagle (scala211_2) $ mvn install -DskipTests -Dcobertura.skip=true -Drat.skip=true -Dcheckstyle.skip=true -Dscala-2.11 -Pscala-2.11 -Pscalding -Psparkr

[ERROR] /Users/pwagle/workspace/zeppelin/incubator-zeppelin-prasadwagle/spark/src/main/java/org/apache/zeppelin/spark/SparkInterpreter.java:[525,20] package MutableSettings does not exist
```

**Comment by lresende** [comment]
@prasadwagle Looks like a merge conflict, waiting for local build before pushing a fix for this.

File: README.md [hunk 3]
```diff
@@ -259,6 +259,14 @@ And browse [localhost:8080](localhost:8080) in your browser.
 
 For configuration details check __`./conf`__ subdirectory.
 
+### Building for Scala 2.11
+
+To produce a Zeppelin package compiled with Scala 2.11, use the -Dscala-2.11 property:
+
+```
+mvn clean package -Pspark-1.6 -Phadoop-2.4 -Pyarn -Ppyspark -Dscala-2.11 -DskipTests clean install
```
Comment (prasadwagle) [inline README.md]: Do we need the -Pscala-2.11 option?

Comment (lresende) [inline README.md]: It's not -P but -D as in a property. If none is provided it takes as Scala 2.10

**Comment by lresende** [comment]
Ok, things are looking better now, the branch is rebased and I have started more testing based on Zeppelin and Spark 1.6.1 both compiled with Scala 2.11. I can run parts of the Zeppelin tutorial notebook, but the sql queries are hanging on the zeppelin side and I am investigating it now.

**Comment by lresende** [comment]
Ok, looks like the hanging I was seeing was mostly a local issue in my Spark conf and is now fixed. 

I have Zeppelin and Spark built with Scala 2.11, and the tutorial notebook works well, I can also update the interpreter properties and that works well as well. Export is working, but Importing as mentioned by @chbrown just don't do anything. I will try with master and see if this is an issue specific to the scala 2.11 branch or not.

Btw,  I am not sure if the CI build these days is helping or not, as it's very hard to trust that failures are related to changes.

**Comment by lresende** [comment]
@Leemoonsoo What should be our next step here ?

**Comment by Leemoonsoo** [comment]
@lresende we have some problem on CI build nowadays, but i can see an error comes from this branch with the second test profile (with scala-2.11). Let me take a look

```
org.apache.zeppelin.interpreter.LazyOpenInterpreter@5275ffcf
Exception in thread "pool-1-thread-3" java.lang.NoSuchMethodError: org.apache.spark.repl.SparkILoop.intp()Lscala/tools/nsc/interpreter/IMain;
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:553)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:69)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.getProgress(LazyOpenInterpreter.java:110)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer.getProgress(RemoteInterpreterServer.java:404)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Processor$getProgress.getResult(RemoteInterpreterService.java:1509)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Processor$getProgress.getResult(RemoteInterpreterService.java:1494)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-1-thread-2" java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
	at org.apache.zeppelin.rinterpreter.RContext$.apply(RContext.scala:280)
	at org.apache.zeppelin.rinterpreter.RInterpreter.rContext$lzycompute(RInterpreter.scala:44)
	at org.apache.zeppelin.rinterpreter.RInterpreter.rContext(RInterpreter.scala:44)
	at org.apache.zeppelin.rinterpreter.RInterpreter.getScheduler(RInterpreter.scala:95)
	at org.apache.zeppelin.rinterpreter.KnitR.getScheduler(KnitR.java:98)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.getScheduler(LazyOpenInterpreter.java:116)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer.getStatus(RemoteInterpreterServer.java:502)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Processor$getStatus.getResult(RemoteInterpreterService.java:1590)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Processor$getStatus.getResult(RemoteInterpreterService.java:1575)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lresende** [comment]
@Leemoonsoo great, let me investigate the issue

**Comment by Leemoonsoo** [comment]
@lresende I've made PR https://github.com/lresende/incubator-zeppelin/pull/2 that fixes scala 2.11 test profile. Please take a look and merge if it looks fine.

**Comment by lresende** [comment]
@Leemoonsoo Thanks for your help, this is now rebased and most of the test jobs are passing, except with one issue that I am seeing in Travis, but seems to work ok locally:
...
[INFO] Zeppelin: Display system apis ...................... FAILURE [  2.747 s]
...
[31m*** RUN ABORTED ***[0m
[31m  java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;[0m
[31m  at org.apache.zeppelin.display.angular.AbstractAngularElemTest$$anonfun$1.apply$mcV$sp(AbstractAngularElemTest.scala:62)[0m
[31m  at org.apache.zeppelin.display.angular.AbstractAngularElemTest$$anonfun$1.apply(AbstractAngularElemTest.scala:59)[0m
[31m  at org.apache.zeppelin.display.angular.AbstractAngularElemTest$$anonfun$1.apply(AbstractAngularElemTest.scala:59)[0m
[31m  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)[0m
[31m  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)[0m
[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m
[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m
[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m
[31m  at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)[0m
[31m  at org.scalatest.Suite$class.withFixture(Suite.scala:1122)[0m

Any ideas ?

**Comment by Leemoonsoo** [comment]
If you see lines above, scalatest plugin works with scala-2.10 libraries.
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Zeppelin: Display system apis 0.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.pom (2 KB at 31.2 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.10/2.2.4/scalatest_2.10-2.2.4.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.10/2.2.4/scalatest_2.10-2.2.4.pom (6 KB at 210.9 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.pom (2 KB at 86.2 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.jar
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.10/2.2.4/scalatest_2.10-2.2.4.jar
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.jar
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.jar (3129 KB at 15260.4 KB/sec)
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.jar (6964 KB at 26886.7 KB/sec)
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.10/2.2.4/scalatest_2.10-2.2.4.jar (7358 KB at 25635.6 KB/sec)
```

It's because of `-Dscala-2.11` flag is not effective in testing. 
I think you'll need move `-Dscala-2.11` (and `-Dscala-2.10`) flag from `BUILD_FLAG` to `PROFILE` in .travis.yml

**Comment by lresende** [comment]
We finally got a green build with Scala 2.11 thanks for @Leemoonsoo help on resolving the couple remaining issues... I now also rebased to latest master and this PR should be ready to final review.

**Comment by Leemoonsoo** [comment]
@lresende Could you trigger CI again and see if scala-2.11 profile pass the flaky test?

**Comment by lresende** [comment]
@Leemoonsoo All green again.

**Comment by Leemoonsoo** [comment]
@lresende Awesome!

Tested and Looks good to me!

File: README.md (hunk 3 above)
Comment (bzz) [inline README.md]: Should not it be now both, `-Pscala-2.11` and `-Dscala-2.11` here, to match the CI above?

File: spark/src/main/java/org/apache/zeppelin/spark/SparkInterpreter.java [hunk 4]
```diff
@@ -1025,4 +1129,119 @@ public ZeppelinContext getZeppelinContext() {
   public SparkVersion getSparkVersion() {
     return sparkVersion;
   }
+
+  private Object invokeMethod(Object o, String name) {
+    return invokeMethod(o, name, new Class[]{}, new Object[]{});
+  }
+
+  private Object invokeMethod(Object o, String name, Class [] argTypes, Object [] params) {
```
Comment (bzz) [inline spark/src/main/java/org/apache/zeppelin/spark/SparkInterpreter.java]: It's awesome, you did a lot of work to get both Scala 2.10 and 2.11 supported!

Probably a nit, but how do you think, shall these guys be pulled up to some common ancestor to avoid duplication between `DepInterpreter` and  `SparkInterpreter`? Or may be just extracted and re-used?

**Comment by bzz** [comment]
Looks 👍 💯  to me

**Comment by lresende** [comment]
@bzz and @Leemoonsoo 

I have updated the readme to match the ci, and also refactored the reflection utility methods to a separate class.

**Comment by Leemoonsoo** [comment]
Looks like there were some network problem on last CI bulid. Could you trigger ci once again and see if it goes to green?

**Comment by lresende** [comment]
@Leemoonsoo all back to green

**Comment by Leemoonsoo** [comment]
Looks good to me!

**Comment by bzz** [comment]
Looks great to me! Thank you @lresende 

Let's merge if there is no further discussion

**Comment by Leemoonsoo** [comment]
Merging it into master and branch-0.6

**Comment by bzz** [comment]
@Leemoonsoo could you into non-trivial merge conflicts that happen on merging to `branch-0.6` ?

**Comment by Leemoonsoo** [comment]
@bzz Sure
